# Generated by Django 2.2.6 on 2020-02-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_auto_20200227_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('archived', 'Archived'), ('unread', 'Unread')], default='unread', max_length=10),
        ),
    ]
