# Generated by Django 2.2.6 on 2020-02-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_auto_20200227_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('archived', 'Archived'), ('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=10),
        ),
    ]
