# Generated by Django 2.2.6 on 2020-02-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_auto_20200227_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('archived', 'Archived'), ('read', 'Read')], default='unread', max_length=10),
        ),
    ]
