# Generated by Django 2.2.6 on 2020-02-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0019_auto_20200227_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('archived', 'Archived')], default='unread', max_length=10),
        ),
    ]
