# Generated by Django 2.2.6 on 2020-03-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0021_auto_20200227_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('archived', 'Archived'), ('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
