# Generated by Django 2.2.13 on 2021-01-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0027_auto_20210112_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('archived', 'Archived'), ('read', 'Read')], default='unread', max_length=10),
        ),
    ]
