# Generated by Django 2.2.13 on 2021-03-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0030_auto_20210118_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('archived', 'Archived'), ('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=10),
        ),
    ]
