# Generated by Django 3.0.13 on 2021-03-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0032_auto_20210303_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('archived', 'Archived')], default='unread', max_length=10),
        ),
    ]
