# Generated by Django 2.2.6 on 2020-01-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0012_auto_20200112_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
