# Generated by Django 2.2.6 on 2020-02-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0014_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/images/default-avatar.png', null=True, upload_to='images'),
        ),
    ]
