# Generated by Django 2.2.6 on 2020-02-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0016_auto_20200227_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='lastname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
