# Generated by Django 2.2.6 on 2020-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0017_auto_20200227_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
