# Generated by Django 2.2.6 on 2020-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0018_auto_20200227_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
