# Generated by Django 2.2.6 on 2020-03-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0020_auto_20200304_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
