# Generated by Django 2.2.6 on 2020-03-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0021_remove_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cover',
            field=models.ImageField(blank=True, default='/images/project-1.png', null=True, upload_to='images'),
        ),
    ]
