# Generated by Django 2.2.13 on 2021-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0025_auto_20210112_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
