# Generated by Django 3.0.13 on 2021-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0027_auto_20210302_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
